version: '3.8'

services:
  web:
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
      - ./src/alembic.ini:/code/alembic.ini
      - ./src/migrations:/code/migrations

  # worker:
  #   volumes:
  #     - ./src/app:/code/app
  #     - ./src/.env:/code/.env

  #-------- uncomment to run tests --------
  # pytest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./src/.env
  #   depends_on:
  #     - db
  #     - create_superuser
  #     - redis
  #   command: python -m pytest ./tests
  #   volumes:
  #     - .:/code
