"""empty message

Revision ID: 4535dd7bf88d
Revises: 92639a1e1ecc
Create Date: 2024-05-11 20:52:19.886436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4535dd7bf88d'
down_revision: Union[str, None] = '92639a1e1ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_group_link_created_by_user_id', table_name='transaction_group_link')
    op.drop_index('ix_transaction_group_link_created_by_user_uuid', table_name='transaction_group_link')
    op.drop_index('ix_transaction_group_link_group_id', table_name='transaction_group_link')
    op.drop_index('ix_transaction_group_link_group_uuid', table_name='transaction_group_link')
    op.drop_index('ix_transaction_group_link_id', table_name='transaction_group_link')
    op.drop_index('ix_transaction_group_link_is_deleted', table_name='transaction_group_link')
    op.drop_index('ix_transaction_group_link_transaction_id', table_name='transaction_group_link')
    op.drop_index('ix_transaction_group_link_transaction_uuid', table_name='transaction_group_link')
    op.drop_index('ix_transaction_group_link_uuid', table_name='transaction_group_link')
    op.drop_table('transaction_group_link')
    op.drop_index('ix_user_group_link_group_id', table_name='user_group_link')
    op.drop_index('ix_user_group_link_group_uuid', table_name='user_group_link')
    op.drop_index('ix_user_group_link_id', table_name='user_group_link')
    op.drop_index('ix_user_group_link_user_id', table_name='user_group_link')
    op.drop_index('ix_user_group_link_user_role', table_name='user_group_link')
    op.drop_index('ix_user_group_link_user_uuid', table_name='user_group_link')
    op.drop_index('ix_user_group_link_uuid', table_name='user_group_link')
    op.drop_table('user_group_link')
    op.drop_index('ix_transaction_tag_tag_id', table_name='transaction_tag')
    op.drop_index('ix_transaction_tag_tag_uuid', table_name='transaction_tag')
    op.drop_index('ix_transaction_tag_transaction_id', table_name='transaction_tag')
    op.drop_index('ix_transaction_tag_transaction_uuid', table_name='transaction_tag')
    op.drop_table('transaction_tag')
    op.drop_index('ix_transaction_purchase_category_id', table_name='transaction')
    op.drop_index('ix_transaction_purchase_category_uuid', table_name='transaction')
    op.drop_constraint('transaction_purchase_category_id_fkey', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'purchase_category_id')
    op.drop_column('transaction', 'purchase_category_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('purchase_category_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('purchase_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('transaction_purchase_category_id_fkey', 'transaction', 'purchase_category', ['purchase_category_id'], ['id'])
    op.create_index('ix_transaction_purchase_category_uuid', 'transaction', ['purchase_category_uuid'], unique=False)
    op.create_index('ix_transaction_purchase_category_id', 'transaction', ['purchase_category_id'], unique=False)
    op.create_table('transaction_tag',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='transaction_tag_tag_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_tag_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id', name='transaction_tag_pkey')
    )
    op.create_index('ix_transaction_tag_transaction_uuid', 'transaction_tag', ['transaction_uuid'], unique=False)
    op.create_index('ix_transaction_tag_transaction_id', 'transaction_tag', ['transaction_id'], unique=False)
    op.create_index('ix_transaction_tag_tag_uuid', 'transaction_tag', ['tag_uuid'], unique=False)
    op.create_index('ix_transaction_tag_tag_id', 'transaction_tag', ['tag_id'], unique=False)
    op.create_table('user_group_link',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_role', postgresql.ENUM('ADMIN', 'MEMBER', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='user_group_link_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_group_link_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_group_link_pkey')
    )
    op.create_index('ix_user_group_link_uuid', 'user_group_link', ['uuid'], unique=True)
    op.create_index('ix_user_group_link_user_uuid', 'user_group_link', ['user_uuid'], unique=False)
    op.create_index('ix_user_group_link_user_role', 'user_group_link', ['user_role'], unique=False)
    op.create_index('ix_user_group_link_user_id', 'user_group_link', ['user_id'], unique=False)
    op.create_index('ix_user_group_link_id', 'user_group_link', ['id'], unique=True)
    op.create_index('ix_user_group_link_group_uuid', 'user_group_link', ['group_uuid'], unique=False)
    op.create_index('ix_user_group_link_group_id', 'user_group_link', ['group_id'], unique=False)
    op.create_table('transaction_group_link',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name='transaction_group_link_created_by_user_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='transaction_group_link_group_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_group_link_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transaction_group_link_pkey')
    )
    op.create_index('ix_transaction_group_link_uuid', 'transaction_group_link', ['uuid'], unique=True)
    op.create_index('ix_transaction_group_link_transaction_uuid', 'transaction_group_link', ['transaction_uuid'], unique=True)
    op.create_index('ix_transaction_group_link_transaction_id', 'transaction_group_link', ['transaction_id'], unique=True)
    op.create_index('ix_transaction_group_link_is_deleted', 'transaction_group_link', ['is_deleted'], unique=False)
    op.create_index('ix_transaction_group_link_id', 'transaction_group_link', ['id'], unique=True)
    op.create_index('ix_transaction_group_link_group_uuid', 'transaction_group_link', ['group_uuid'], unique=False)
    op.create_index('ix_transaction_group_link_group_id', 'transaction_group_link', ['group_id'], unique=False)
    op.create_index('ix_transaction_group_link_created_by_user_uuid', 'transaction_group_link', ['created_by_user_uuid'], unique=False)
    op.create_index('ix_transaction_group_link_created_by_user_id', 'transaction_group_link', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###
