"""empty message

Revision ID: cfef1643a23a
Revises: f6be35bca939
Create Date: 2024-04-28 18:43:20.362691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfef1643a23a'
down_revision: Union[str, None] = 'f6be35bca939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'description')
    op.drop_index('ix_transaction_tag_id', table_name='transaction')
    op.drop_index('ix_transaction_tag_uuid', table_name='transaction')
    op.drop_constraint('transaction_tag_id_fkey', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'tag_uuid')
    op.drop_column('transaction', 'tag_id')
    op.drop_index('ix_transaction_item_tag_id', table_name='transaction_item')
    op.drop_index('ix_transaction_item_tag_uuid', table_name='transaction_item')
    op.drop_constraint('transaction_item_tag_id_fkey', 'transaction_item', type_='foreignkey')
    op.drop_column('transaction_item', 'tag_uuid')
    op.drop_column('transaction_item', 'tag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_item', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transaction_item', sa.Column('tag_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('transaction_item_tag_id_fkey', 'transaction_item', 'tag', ['tag_id'], ['id'])
    op.create_index('ix_transaction_item_tag_uuid', 'transaction_item', ['tag_uuid'], unique=False)
    op.create_index('ix_transaction_item_tag_id', 'transaction_item', ['tag_id'], unique=False)
    op.add_column('transaction', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('tag_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('transaction_tag_id_fkey', 'transaction', 'tag', ['tag_id'], ['id'])
    op.create_index('ix_transaction_tag_uuid', 'transaction', ['tag_uuid'], unique=False)
    op.create_index('ix_transaction_tag_id', 'transaction', ['tag_id'], unique=False)
    op.add_column('tag', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
